fix: make keys optional in object parsing
sapphiredev/shapeshift pull request #134
Opened 2022-06-23 04:48 UTC by imranbarbhuiya

This pr makes keys optional instead of `| undefined`.
This is a hacky solution, I've tried various ways for 1 hr but can't find a better way of doing it, so if anyone has a better solution then lmk.

2022-06-23 06:26 UTC, favna requested changes

2022-06-23 06:26 UTC, favna commented on src/lib/util-types.ts
> +	[K in keyof T as undefined extends T[K] ? K : never]?: Exclude<T[K], undefined>;
```suggestion
	[K in keyof T as undefined extends T[K] ? K : never]+?: Exclude<T[K], undefined>;
```

This will actually make it optional

2022-06-26 14:40 UTC, favna approved these changes

2022-06-26 14:45 UTC, vladfrangu approved these changes

2022-06-26 14:45 UTC, kyranet approved these changes

2022-06-26 15:00 UTC, merged