build: fix djs/builder type error
sapphiredev/shapeshift pull request #159
Opened 2022-07-13 12:09 UTC by imranbarbhuiya

similar to https://github.com/sapphiredev/shapeshift/pull/153
this pr tried to fix the djs/builder error.
djs/builder was compiled with an older version of `shapeshift` when `ArrayValidator` was accepting any type as the first generic type. But after https://github.com/sapphiredev/shapeshift/pull/140, it expects  `unknown[]` type. That's why users are getting type errors. 

> **Note**
`type makeArray<T> = T extends any[] ? T : T[];` can be removed by making `P` 2nd generic type instead of 3rd. But then it'll throw the same error for packages that were compiled with a new version of `shapeshift` which's 2nd param is not an array type.
So in the future, when we'll release v4, we can remove it

2022-07-13 20:37 UTC, favna requested changes

2022-07-13 20:37 UTC, favna commented on src/validators/ArrayValidator.ts
> +export class ArrayValidator<T, I = makeArray<T>[number], P extends unknown[] = makeArray<T>> extends BaseValidator<P> {
Please add the TODO from the PR description here in the code as well with: `// TODO (v4): `

2022-07-14 06:04 UTC, favna approved these changes

2022-07-14 08:22 UTC, imranbarbhuiya commented
I just noticed that if anyone has `ArrayValidator<string[]>` then
without this pr,  return type of `.parse` will be `string[]`
with this pr, it'll be `string`. 

So we are again breaking. So I'm closing this pr and let's wait for a new builder release. 
Anyone who has the issue they either need to add a resolution of `^3.4.0` or `skipLibCheck` before /builder releases a new version.

2022-07-14 08:22 UTC, closed without merging