feat: add bigint methods
sapphiredev/shapeshift pull request #32
Opened 2022-02-09 23:54 UTC by Khasms

2022-02-09 23:59 UTC, kyranet requested changes

2022-02-09 23:59 UTC, kyranet commented on src/validators/BigIntValidator.ts
> +		return this.transform(((value) => (value < 0 ? -value : value)) as (value: bigint) => T);
```suggestion
		return this.transform((value) => (value < 0 ? -value : value) as T);
```

2022-02-09 23:59 UTC, kyranet commented on src/validators/BigIntValidator.ts
> +		return this.transform(((value) => BigInt.asIntN(bits, value)) as (value: bigint) => T);
```suggestion
		return this.transform((value) => BigInt.asIntN(bits, value) as T);
```

2022-02-09 23:59 UTC, kyranet commented on src/validators/BigIntValidator.ts
> +		return this.transform(((value) => BigInt.asUintN(bits, value)) as (value: bigint) => T);
```suggestion
		return this.transform((value) => BigInt.asUintN(bits, value) as T);
```

2022-02-09 23:59 UTC, kyranet commented on tests/validators/bigint.test.ts
> +const unsafeInteger = 242043489611808769n;
They're always safe, and the eslint ignore is unneeded.

2022-02-11 20:16 UTC, favna approved these changes

2022-02-11 20:16 UTC, merged