chore: bundle node util in node env too
sapphiredev/shapeshift pull request #334
Opened 2023-12-17 15:00 UTC by imranbarbhuiya

There are 2 approaches, see first and second commit. In the first approach, we'll need to add the node module name every time we use a new module, in 2nd approach, we'll need to add the deps name every time we add a new deps and don't want to bundle it. 

check [discord channel](https://canary.discord.com/channels/737141877803057244/934614121687687179/1184234577439494334) for more context

fixes: #316

2023-12-18 00:19 UTC, favna requested changes
Add to the top of the tsup config:
```
import { dependencies } from './package.json';
```

Then I think this solution is what we'll go for.

2023-12-18 00:19 UTC, favna commented on tsup.config.ts
> +	external: ['fast-deep-equal', 'lodash'],
```suggestion
	external: Object.keys(dependencies),
```

2024-01-17 07:36 UTC, imranbarbhuiya commented
I was in vacation and after that I forgot about this pr, @favna applied your suggestion in the last commit

2024-01-18 19:02 UTC, favna approved these changes

2024-01-18 19:13 UTC, merged